<?php
/** @var \MSP\TwoFactorAuth\Block\Configure $block */
/** @var \Magento\Framework\Escaper $escaper */

$list = $block->getProvidersList();
?>
<p id="2fa-configure-header">
    Please select one or more Two-Factor Authorization providers to be used
    to authorize admin users
</p>
<div id="2fa-providers-list">
    <?php if (!$list): ?>
        <p class="mage-error">
            No providers are available to select, please configure required 2FA provider settings on the server via CLI
        </p>
    <?php else: ?>
        <form class="tfa-configure-providers" method="post" action="<?= $block->getActionUrl() ?>">
            <ul class="msp-tfa-provider_list">
                <?php foreach ($list as $providerData): ?>
                    <li class="msp-tfa-provider">
                        <input type="checkbox"
                               name="tfa_selected[<?= $escaper->escapeHtmlAttr($providerData['code']) ?>]"
                               class="tfa-checkbox"
                               id="2fa_checkbox-<?= $escaper->escapeHtmlAttr($providerData['code']) ?>"/>
                        <label for="2fa_checkbox-<?= $escaper->escapeHtmlAttr($providerData['code']) ?>">
                            <img src="<?= $escaper->escapeHtmlAttr($providerData['icon']) ?>"/>
                            <span><?= $escaper->escapeHtml($providerData['name']) ?></span>
                        </label>
                    </li>
                <?php endforeach; ?>
            </ul>
            <br/>
            <?= $block->getBlockHtml('formkey') ?>
            <input type="submit" value="Apply" class="action-primary" />
        </form>
    <?php endif; ?>
</div>
